In [2]:
import numpy as np

In [8]:
def dia_dom(A):
    n = len(A)
    for i in range(n):
        diagonal = abs(A[i][i])
        row_sum = 0
        for j in range(n):
            if i != j:
                row_sum += abs(A[i][j])
        if diagonal < row_sum:
            return False
    return True

In [10]:
B = np.array([[100, 2, 3, 0, 0],
            [2, 1000, 2, 3, 0],
            [3, 2, 100, 2, 3],
            [0, 3, 2, 100, 2],
            [0, 0, 3, 2, 1000]], dtype=float)
print(B)
print("Is Matrix Diagonally dominant? ", dia_dom(B))

[[ 100.    2.    3.    0.    0.]
 [   2. 1000.    2.    3.    0.]
 [   3.    2.  100.    2.    3.]
 [   0.    3.    2.  100.    2.]
 [   0.    0.    3.    2. 1000.]]
Is Matrix Diagonally dominant?  True
